name: Docker builds and checks

on: [ push ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-24.04, ubuntu-rolling, fedora42, fedora-rawhide ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create Docker image
        run: |
          docker build --pull -t ${{ matrix.os }} -f qemu-ci/Dockerfile-${{ matrix.os }} .

      - name: Build QEMU and run checks
        run: |
          docker run --rm -t ${{ matrix.os }} bash -c "./qemu-ci/build-${{ matrix.os }}.sh"
